In [43]:
import numpy as np
import matplotlib.pyplot as plt

In [44]:
X=np.array([54,56,78,89,53,37,29,26,39,18])
Y=np.array([1,1,1,1,1,0,0,0,0,0])


In [45]:
X=X.reshape([X.shape[0],1])

In [46]:
ones=np.ones([X.shape[0],1])

In [47]:
X=np.concatenate((ones,X),axis=1)

In [48]:
X

array([[ 1., 54.],
       [ 1., 56.],
       [ 1., 78.],
       [ 1., 89.],
       [ 1., 53.],
       [ 1., 37.],
       [ 1., 29.],
       [ 1., 26.],
       [ 1., 39.],
       [ 1., 18.]])

In [50]:
X2

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [54.],
       [56.],
       [78.],
       [89.],
       [53.],
       [37.],
       [29.],
       [26.],
       [39.],
       [18.]])

In [51]:
theta=np.zeros(X.shape[1])

In [52]:
theta

array([0., 0.])

In [53]:
def hypothesis(X,thata):
    R=1/(1+np.exp(-(X.dot(theta.T))))
    return R

In [54]:
hypothesis(X,theta)

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

In [55]:
def loss(m,X,Y,hyp):
    Result=((-1/m)*np.sum((Y*np.log(hyp))+(1-Y)*np.log(1-hyp)))
    return Result

In [56]:
loss(X.shape[0],X,Y,hypothesis(X,theta))

0.6931471805599454

In [57]:
def gradient(m,X,Y,hyp):
    result=((1/m)*np.dot(X.T,(hyp-Y)))
    return result

In [58]:
gradient(X.shape[0],X,Y,hypothesis(X,theta))

array([ 0.  , -9.05])

In [61]:
#training loop
los=[]
step=[]
lr=0.0001
for i in range(10):
    step.append(i)
    H=hypothesis(X,theta)
    l=loss(X.shape[0],X,Y,hypothesis(X,theta))
    los.append(l)
    d=gradient(X.shape[0],X,Y,hypothesis(X,theta))
    theta=theta-lr*d
    print(f'epoch={i},loss={l:.3f}')



epoch=0,loss=1.399
epoch=1,loss=1.380
epoch=2,loss=1.361
epoch=3,loss=1.342
epoch=4,loss=1.324
epoch=5,loss=1.305
epoch=6,loss=1.287
epoch=7,loss=1.268
epoch=8,loss=1.250
epoch=9,loss=1.232
