In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4,5])

In [3]:
x

array([1, 2, 3, 4, 5])

In [4]:
x.shape

(5,)

In [5]:
x=x.reshape([x.shape[0],1])

In [6]:
x.shape

(5, 1)

In [7]:
result=x*2

In [8]:
result

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])

In [10]:
x2=np.array([2,3,4,6,7])
x2=x2.reshape([x2.shape[0],1])

In [11]:
x2

array([[2],
       [3],
       [4],
       [6],
       [7]])

In [13]:
x3=np.concatenate((x,x2),axis=1)

In [14]:
x3

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 6],
       [5, 7]])

In [19]:
x3.shape

(5, 2)

In [15]:
x4=np.concatenate((x,x2),axis=0)

In [16]:
x4

array([[1],
       [2],
       [3],
       [4],
       [5],
       [2],
       [3],
       [4],
       [6],
       [7]])

In [17]:
r=x3*2

In [18]:
r

array([[ 2,  4],
       [ 4,  6],
       [ 6,  8],
       [ 8, 12],
       [10, 14]])

In [21]:
x5=np.random.rand(5,2)

In [22]:
x5

array([[0.2747047 , 0.50765702],
       [0.76350859, 0.16436539],
       [0.70231655, 0.57195384],
       [0.74316257, 0.48921061],
       [0.64197536, 0.58282173]])

In [23]:
x5.shape

(5, 2)

In [24]:
result=x3*x5

In [26]:
result.shape

(5, 2)

In [28]:
x3=x3.T

In [30]:
x3.shape

(2, 5)

In [31]:
result=np.dot(x3,x5)

In [32]:
res=np.dot(x5,x3)

In [34]:
result.shape

(2, 2)

In [35]:
res

array([[1.29001874, 2.07238046, 2.85474219, 4.14476093, 4.92712265],
       [1.09223936, 2.02011334, 2.94798732, 4.04022668, 4.96810066],
       [1.84622423, 3.12049462, 4.39476501, 6.24098924, 7.51525963],
       [1.72158379, 2.95395696, 4.18633014, 5.90791393, 7.14028711],
       [1.80761882, 3.03241591, 4.257213  , 6.06483182, 7.28962891]])

In [36]:
res.shape

(5, 5)